"""Chemical potential generated by the McKean--Vlasov free energy."""

from __future__ import annotations

import numpy as np

from ..mechanics.density_scaling import DensityConvention, expected_density_mass

def chemical_potential_joule(
    density_per_m2: np.ndarray,
    thermal_energy_joule: float,
    reference_density_per_m2: float,
    external_potential_joule: np.ndarray,
    pair_convolution_joule: np.ndarray,
    *,
    diagnostic_density_floor_per_m2: float | None = None,
    density_convention: DensityConvention = DensityConvention.PROBABILITY,
    population_count: int | None = None,
) -> np.ndarray:
    """Return ``mu=kBT log(rho/rho_ref)+V+W*rho`` in joules.

    A positive floor is permitted only for finite diagnostic output. The flux
    implementation evaluates diffusion separately and does not rely on this
    floor, so it does not create artificial transport from empty cells.
    """

    density = np.asarray(density_per_m2, dtype=np.float64)
    external = np.asarray(external_potential_joule, dtype=np.float64)
    interaction = np.asarray(pair_convolution_joule, dtype=np.float64)
    if density.shape != external.shape or density.shape != interaction.shape:
        raise ValueError("density and potentials must have matching shapes")
    if np.any(density < 0.0) or not np.all(np.isfinite(density)):
        raise ValueError("density must be finite and non-negative")
    if not np.all(np.isfinite(external)) or not np.all(np.isfinite(interaction)):
        raise ValueError("external and interaction potentials must be finite")
    expected_density_mass(density_convention, population_count)
    scalar_values = np.asarray(
        [thermal_energy_joule, reference_density_per_m2], dtype=np.float64
    )
    if not np.all(np.isfinite(scalar_values)) or np.any(scalar_values <= 0.0):
        raise ValueError("thermal energy and reference density must be positive")
    if diagnostic_density_floor_per_m2 is None:
        safe_density = density
    else:
        floor = float(diagnostic_density_floor_per_m2)
        if not np.isfinite(floor) or floor <= 0.0:
            raise ValueError("diagnostic density floor must be positive")
        safe_density = np.maximum(density, floor)
    with np.errstate(divide="ignore"):
        entropy_part = thermal_energy_joule * np.log(
            safe_density / reference_density_per_m2
        )
    return entropy_part + external + interaction
